### ISSUE TITLE
move childrens lit categories to directory

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/uwlswd_vocabs#23]
Starting point is the to-do list from #22 .

- [x] Copy RDF/XML data to new location
- [x] Pre-process RDF/XML
   - [x] Increment version number in RDF/XML as revision; dct:hasFormat values changing
   - [x] Remove dct:hasFormat triples
   - [x] Add missing void:feature per https://github.com/uwlib-cams/uwlswd_vocabs/issues/26
- [x] main.py - change $rdf2rdfa_stylesheet to xsl/rdf2htmlrdfa-plusdc.xsl \*
- [x] run main.py
- [x] check new dct:hasFormat values
- [x] check triples in new serializations against old \*\*
- [x] main.py change $rdf2rdfa_stylesheet *back to* xsl/rdf2htmlrdfa.xsl \*
- [x] Update DataCite XML
   - [ ] ~Remove version number~ no version number in existing DataCite XML
   - [x] Add //title/@titleType="AlternativeTitle"
   - [x] Update resourceType per draft BMPs
   - [x] ~Update~ **Add** //formats/format per https://github.com/uwlib-cams/uwlswd/issues/51 
   - [x] Add //sizes/size 
   - [ ] ~Update schema location per~ https://github.com/uwlib-cams/uwlswd/issues/50 - no need
- [x] ***commit + push data to new location***
- [x] Update DOI at DataCite Fabrica
   - [x] Upload XML
   - [x] Update URL
- [x] Confirm DOI dereferences to new location
- [x] Delete RDF/XML data at old location

\* *See [Run main.py to serialize data](https://github.com/uwlib-cams/uwlswd/wiki/workflow#5-run-mainpy-to-serialize-data)*
\*\* *Only checked number of triples in the graph*

**Comment by cspayne** [comment]
> RE: **check triples in new serializations against old**
> 
> RDF/XML prior to reserialization = 89 triples RDF/XML after reserialization = 117 triples!?

Was this after running main.py??

**Comment by briesenberg07** [comment]
Hi @cspayne   
> Was this after running main.py??  

It was. But the problem seems to have resolved itself! Only one additional triple now, which is expected since I added a triple per https://github.com/uwlib-cams/uwlswd_vocabs/issues/26 . Still not sure what was happening earlier... (I 'started over from scratch' -- copying the old data once again --- this time running main.py).
```
# old
>>> from rdflib import Graph
>>> g = Graph()
>>> g.parse("gitrepos/uwlswd_vocabs/linked_data_vocabularies_childrens_literature_categories.rdf")
<Graph identifier=N82135c34f28e4ba3a26d0104d91a78aa (<class 'rdflib.graph.Graph'>)>
>>> len(g)
89
```
```
# new
>>> from rdflib import Graph
>>> g = Graph()
>>> g.parse("gitrepos/uwlswd_vocabs/childrens_literature_categories/linked_data_vocabularies_childrens_literature_categories.rdf")
<Graph identifier=N6ba0cfaa92d14bf08c41ef37f1b92461 (<class 'rdflib.graph.Graph'>)>
>>> len(g)
90
```

**Comment by cspayne** [comment]
@briesenberg07 
It looks like you may have run an older version of the main.py and related scripts. 

I made some changes following Theo's feedback and pushed those, so that:
- the 'html' hasFormat triple is not in the RDFa table
- The iris in the predicate column are accurate and dereference properly
- alternate name is available in schema.org and at top-of-page (note that the property should be changed to **dcterms:alternative**)

If you pull the update and re-run the script, this should all be working now. 
I also noted that the language property is missing in this resource's DataCite metadata (and thus, also in schema.org)

As a final aside, I am going to update the xsl so that the 'rdf' hasFormat is added with the correct prefix based on the input, I believe we can do this now that we've figured out how to access these thanks to Theo!

**Comment by briesenberg07** [comment]
@cspayne I think you're right! I realized after running that there were lots of changes...
@briesenberg07 run main.py again following pull
